"""Golden vectors for zeptly-jcs-v1: parser, JCS, payload text policy, artifact digest and directory seal.

The vector file is generated by tests/vectors/make_vectors.py (which cross-checks zskill against the stdlib-only
reference implementation in tests/vectors/reference_zeptly_jcs_v1.py). The committed file must equal the generator output.
These are Skills-generated vectors: the shared protocol vector distribution was not supplied to this registry.
"""
import json
import subprocess
import sys
import copy
from pathlib import Path

import pytest

from zskill.bundle import Bundle, BundleError, canonical_json, manifest_projection, payload_text_problem
from zskill.errors import CanonicalizationError, YamlError
from zskill.yamlsubset import load_yaml, load_yaml_text

VEC = Path(__file__).parent / "vectors"
DATA = json.loads((VEC / "zeptly-jcs-v1.skills-generated.json").read_text(encoding="utf-8"))
sys.path.insert(0, str(VEC))
import reference_zeptly_jcs_v1 as R  # noqa: E402

BUNDLE = DATA["bundle"]
FILES = {f["path"]: bytes.fromhex(f["contentHex"]) for f in BUNDLE["files"]}


def test_vector_file_is_current():
    r = subprocess.run([sys.executable, str(VEC / "make_vectors.py"), "--check"], capture_output=True, text=True)
    assert r.returncode == 0, r.stderr


def test_independent_reference_passes_all_vectors():
    assert [n for n, got, want in R.run(DATA) if got != want] == []


def test_algorithm_identifier():
    assert DATA["digestAlgorithm"] == "zeptly-jcs-v1"


@pytest.mark.parametrize("c", [c for c in DATA["jcs"] if "expect" in c], ids=lambda c: c["name"])
def test_jcs_vectors(c):
    assert canonical_json(json.loads(c["input"])).decode("utf-8") == c["expect"]


@pytest.mark.parametrize("c", [c for c in DATA["jcs"] if "reject" in c], ids=lambda c: c["name"])
def test_jcs_rejections(c):
    with pytest.raises(CanonicalizationError) as e:
        canonical_json(json.loads(c["input"]))
    assert e.value.code == c["reject"] and e.value.exit_code == 2


def test_jcs_sorts_by_utf16_code_units_not_code_points():
    # U+10000 is D800 DC00 in UTF-16 and sorts before U+FF5E, the opposite of code-point order
    assert canonical_json({"～": 1, "\U00010000": 2}).decode() == '{"\U00010000":2,"～":1}'


def test_jcs_does_not_normalise_unicode_or_line_endings():
    assert canonical_json("é") != canonical_json("é")
    assert canonical_json("a\r\nb") == b'"a\\r\\nb"'  # manifest strings keep their CRLF; escaped, never rewritten


@pytest.mark.parametrize("bad", [{1: "x"}, {"x": {1, 2}}, float("nan"), float("inf"), 2 ** 60])
def test_jcs_rejects_unrepresentable_values(bad):
    with pytest.raises((CanonicalizationError, ValueError, TypeError)):
        canonical_json(bad)


@pytest.mark.parametrize("c", DATA["payloadText"], ids=lambda c: c["name"])
def test_payload_text_vectors(c):
    got = (payload_text_problem(bytes.fromhex(c["inputHex"])) or ("ok",))[0]
    assert got == c["expect"]


@pytest.mark.parametrize("c", DATA["parser"], ids=lambda c: c["name"])
def test_parser_vectors(c, tmp_path):
    def parse():
        if "inputHex" in c:
            p = tmp_path / "v.yaml"
            p.write_bytes(bytes.fromhex(c["inputHex"]))
            return load_yaml(p)
        return load_yaml_text(c["yaml"], "v.yaml")
    exp = c["expect"]
    if isinstance(exp, dict) and set(exp) == {"reject"}:
        with pytest.raises(YamlError) as e:
            parse()
        assert e.value.code == exp["reject"] and e.value.exit_code == 2 and e.value.file
    else:
        assert parse() == exp


def _bundle(tmp_path, manifest, files):
    d = tmp_path / "skills" / "x" / "golden.example"
    for p, b in files.items():
        q = d / p
        q.parent.mkdir(parents=True, exist_ok=True)
        q.write_bytes(b)
    return Bundle(root=tmp_path, path=d, tier="skills", manifest=manifest)


def test_expected_projection_digest_and_seal(tmp_path):
    m = BUNDLE["manifest"]
    assert canonical_json(manifest_projection(m)).decode() == BUNDLE["expected"]["projectionJcs"]
    b = _bundle(tmp_path, m, FILES)
    assert b.digest() == BUNDLE["expected"]["artifactDigest"]
    assert b.directory_seal() == BUNDLE["expected"]["directorySeal"]
    assert canonical_json(b.seal_document()).decode() == BUNDLE["expected"]["sealDocumentJcs"]


@pytest.mark.parametrize("mu", BUNDLE["mutations"], ids=lambda m: m["name"])
def test_mutation_vectors(tmp_path, mu):
    m, files = R.apply_mutation(BUNDLE["manifest"], FILES, mu)
    if "expectReject" in mu:
        with pytest.raises(BundleError) as e:
            _bundle(tmp_path, m, files).directory_seal()
        assert e.value.code == mu["expectReject"] and e.value.exit_code == 2
        return
    b = _bundle(tmp_path, m, files)
    assert (b.digest(), b.directory_seal()) == (mu["digest"], mu["seal"])
    base = BUNDLE["expected"]
    assert ("same" if b.digest() == base["artifactDigest"] else "different") == mu["expectDigest"]
    assert ("same" if b.directory_seal() == base["directorySeal"] else "different") == mu["expectSeal"]


def test_digest_excludes_version_maturity_lifecycle_attestations_approvals(tmp_path):
    m = copy.deepcopy(BUNDLE["manifest"])
    m["metadata"].update(version="0.0.1", maturity="candidate", lifecycle="active")
    m["attestations"] = []
    m["security"]["approvals"] = []
    b = _bundle(tmp_path, m, FILES)
    assert b.digest() == BUNDLE["expected"]["artifactDigest"]
    assert b.directory_seal() != BUNDLE["expected"]["directorySeal"]  # the seal binds the version
